name: Go
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: golang:1.13
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go mod download

    - name: Run tests
      env:
        CGO_ENABLED: 0
      run: go test -cover ./...
